spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/elevate}
    username: ${DATABASE_USERNAME:elevate}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
